import {patch, checkPatchValue, isSomeKind, isNoneKind} from './internal';
export const __internal = {patch, checkPatchValue, isSomeKind, isNoneKind};
export * from './option';
export * from './guards';
export * from './fromNullable';
export * from './unwrapping';
export * from './transforming';
export * from './flat';
export * from './apply';
export * from './legacy';
